openapi: 3.0.0
info:
  title: Nutrition Agent Tools
  version: 1.0.0
paths:
  /get_recipe:
    get:
      summary: Get a recipe based on nutritional needs
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
        - in: query
          name: dietary_restrictions
          schema:
            type: string
      responses:
        '200':
          description: Recipe returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipe:
                    type: string
                  ingredients:
                    type: array
                    items:
                      type: string
  /log_meal:
    post:
      summary: Log a meal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                meal:
                  type: string
                calories:
                  type: integer
      responses:
        '200':
          description: Meal logged
